package lt.vu.mybatis.model;

import java.util.List;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    private String Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    private String Surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @return the value of PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    public String getName() {
        return Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @param Name the value for PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.SURNAME
     *
     * @return the value of PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    public String getSurname() {
        return Surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.SURNAME
     *
     * @param Surname the value for PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Wed Apr 10 02:12:58 EEST 2024
     */
    public void setSurname(String Surname) {
        this.Surname = Surname;
    }

    private List<Book> books;

    public List<Book> getBooks() {
        return books;
    }

    public void setBooks(List<Book> books) {
        this.books = books;
    }
}